package com.hexhaki.network;

public enum HakiAction {
    ARMAMENT_TOGGLE,
    OBSERVATION_TOGGLE,
    CONQUEROR_START,
    CONQUEROR_RELEASE,
    CONQUEROR_CYCLE_MODE,
    ACOC_TOGGLE,
    DOMINION_START,
    DOMINION_RELEASE,
    SOVEREIGN_STRIKE,
    SOVEREIGN_STRIKE_RELEASE,
    CONVERGENCE_START,
    CONVERGENCE_RELEASE,
    GALAXY_PUNCH,
    HAKI_LEAP_START,
    HAKI_LEAP_RELEASE,
    HAKI_BLADE_SLASH
}
